export enum ErrorsEnum {
  email_is_already_in_use = 'Email is already in use',
  account_not_found = 'Account not found',
  device_not_found = 'Device not found',
  invalid_password = 'Invalid password',
  only_admin_can_create_an_admin = 'Only admin can create an admin',
  password_is_required = 'Password is required',
  password_must_contain_at_least_one_special_character = 'Password must contain at least one special character',
  password_must_contain_at_least_one_digit = 'Password must contain at least one digit',
  password_must_contain_at_least_one_lowercase_letter = 'Password must contain at least one lowercase letter',
  password_must_contain_at_least_one_uppercase_letter = 'Password must contain at least one uppercase letter',
  password_must_be_at_least_8_characters_long = 'Password must be at least 8 characters long',
  password_and_password_confirmation_do_not_match = 'Password and password confirmation do not match',
  username_must_be_at_least_8_characters_long = 'Username must be at least 8 characters long',
  account_is_inactive = 'This account is inactive, please wait for the administrator to activate your account',
}
